document.addEventListener('DOMContentLoaded', () => {
    const form = document.getElementById('query-form');
    const input = document.getElementById('query-input');
    const chatContainer = document.getElementById('chat-container');
    const welcomeScreen = document.getElementById('welcome-screen');
    const submitBtn = document.getElementById('submit-btn');
    const suggestionsContainer = document.getElementById('suggestions-container');

    // Global function to allow quick prompts to work
    window.fillAndSubmit = function(text) {
        input.value = text;
        form.dispatchEvent(new Event('submit'));
    };

    form.addEventListener('submit', async (e) => {
        e.preventDefault();
        const query = input.value.trim();
        if (!query) return;

        // Clear UI
        if (welcomeScreen) welcomeScreen.style.display = 'none';
        suggestionsContainer.innerHTML = '';
        input.value = '';
        input.blur();

        // Add User Message
        appendMessage(query, 'user');

        // Add Loading Indicator
        const loadingId = addLoading();
        submitBtn.disabled = true;

        try {
            // Fetch from FastAPI
            const response = await fetch('/api/query', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ query })
            });

            const data = await response.json();
            removeLoading(loadingId);
            appendAIMessage(data);
            
            // Handle suggestions generated by the backend
            if (data.suggestions && data.suggestions.length > 0) {
                renderSuggestions(data.suggestions);
            }

        } catch (error) {
            console.error("Error:", error);
            removeLoading(loadingId);
            appendMessage("Connection error. Could not reach the memory engine.", 'ai');
        } finally {
            submitBtn.disabled = false;
            input.focus();
        }
    });

    function appendMessage(text, sender) {
        const div = document.createElement('div');
        div.className = `message ${sender}`;
        div.innerHTML = `<div class="msg-bubble">${escapeHTML(text)}</div>`;
        chatContainer.appendChild(div);
        scrollToBottom();
    }

    function appendAIMessage(data) {
        const div = document.createElement('div');
        div.className = 'message ai';
        
        // Build the Source Tags
        let sourceTags = data.sources.map(s => `<span class="tag">${escapeHTML(s.label)}</span>`).join('');
        if (!sourceTags) sourceTags = '<span class="tag">No sources linked</span>';

        // Build the Reasoning Chain
        let chainTags = data.chain.map(c => `<span class="tag">${escapeHTML(c)}</span>`).join('');
        
        // Build the Graph Context
        let graphReasons = data.graph.reasons.map(r => `<li style="margin-bottom:4px; margin-left: 16px;">${escapeHTML(r)}</li>`).join('');

        // Construct the complex AI payload structure
        div.innerHTML = `
            <div class="msg-bubble">
                <div class="answer-text">${escapeHTML(data.answer).replace(/\n/g, '<br>')}</div>
                
                <div class="meta-container">
                    <div class="meta-header">
                        <span>Engine Diagnostics</span>
                        <span class="confidence">Confidence: ${escapeHTML(data.confidence)}</span>
                    </div>
                    
                    <div class="meta-grid">
                        <div class="meta-box">
                            <div class="meta-title">Execution Chain</div>
                            <div class="tag-list">${chainTags}</div>
                        </div>
                        <div class="meta-box">
                            <div class="meta-title">Retrieved Sources</div>
                            <div class="tag-list">${sourceTags}</div>
                        </div>
                    </div>

                    <div class="meta-box" style="margin-top: -4px;">
                        <div class="meta-title">Graph DB Logic: ${escapeHTML(data.graph.center)}</div>
                        <ul style="color: var(--text-muted); font-size: 13px;">${graphReasons}</ul>
                    </div>
                </div>
            </div>
        `;
        
        chatContainer.appendChild(div);
        scrollToBottom();
    }

    function renderSuggestions(suggestions) {
        suggestionsContainer.innerHTML = suggestions.map(s => 
            `<button onclick="fillAndSubmit('${escapeHTML(s)}')">${escapeHTML(s)}</button>`
        ).join('');
    }

    function addLoading() {
        const id = 'load-' + Date.now();
        const div = document.createElement('div');
        div.className = 'message ai';
        div.id = id;
        div.innerHTML = `
            <div class="msg-bubble loading" style="background: transparent; border: none;">
                <div class="dot"></div><div class="dot"></div><div class="dot"></div>
            </div>
        `;
        chatContainer.appendChild(div);
        scrollToBottom();
        return id;
    }

    function removeLoading(id) {
        const el = document.getElementById(id);
        if (el) el.remove();
    }

    function scrollToBottom() {
        chatContainer.scrollTop = chatContainer.scrollHeight;
    }

    function escapeHTML(str) {
        return str.replace(/[&<>'"]/g, 
            tag => ({
                '&': '&amp;',
                '<': '&lt;',
                '>': '&gt;',
                "'": '&#39;',
                '"': '&quot;'
            }[tag] || tag)
        );
    }
});